### ISSUE TITLE
HOW to connect to CAS server on windows Rstudio?

### ISSUE THREAD

**Issue by roy12369** [sassoftware/R-swat#11]
Hi Expert,
I have successfully connect to CAS Server with the [SAS Viya Doc ](http://documentation.sas.com/?cdcId=pgmcdc&cdcVersion=8.11&docsetId=caspg3r&docsetTarget=p0paczu3x2qu0wn1p94ees7y5ls8.htm&locale=zh-TW ) but I stuck on windows Rstudio.
Could you kindly guide me to connect CAS server with windows RStudio step by step?

**Comment by jld23** [comment]
The code in the [example](https://github.com/sassoftware/R-swat#example) of the readme should get you connected. You'll just need to change the ip address to match your CAS server.
```
> library(swat)

# Connect to CAS
> conn <- swat::CAS('cloud.example.com', 8777)

# Load Iris data set into in-memory table
> iris.ct <- as.casTable(conn, iris)
```
If the package isn't yet installed on your windows box, then refer to [this](https://github.com/sassoftware/R-swat#installation) section.

**Comment by roy12369** [comment]
hi @jld23 ,
sorry for the typo. I have successfully connect using Linux ,but failed on windows.
Here is the error message.
> library(swat)
> conn <- swat::CAS('172.18.106.125', 8777)
Error in value[[3L]](cond) : 
  Could not create object from the extension module.
 You may be attempting to create a binary CAS connection on a platform
 that only supports the CAS REST interface

**Comment by jld23** [comment]
@roy12369, You'll need to specify the protocol and probably the location of your authinfo file.
See [here](https://github.com/sassoftware/R-swat#authinfo-file) for an example.

**Comment by kesmit13** [comment]
@roy12369, the CAS clients do not support binary communication from Windows.  You need to use the HTTP protocol.  That means that you will use the HTTP port of the server rather than the binary port of 8777.

**Comment by kesmit13** [comment]
Actually, it may be that you are using HTTP already since the port number is 8777.  As mentioned, you should try setting the protocol explicitly using protocol='http' and specifying your username and password in the CAS connection call just to verify the connection works.  Then you can switch to authinfo or another form of authentication once you know the most basic connection form works.

**Comment by kesmit13** [comment]
The fact that you are getting an empty response from the server is very strange.  It seems like it should be sending something back even if it's an error message.  You might want to try wrapping your CAS(...) call in httr::with_verbose(...) and see if that provides any clues.

**Comment by kesmit13** [comment]
What happens if you just try to open http://172.18.106.125:8777/cas/ in a web browser from Windows?

**Comment by roy12369** [comment]
Hi @kesmit13 ,

If I connect to  http://172.18.106.125:8777/cas/,the browser shows the message below.
![image](https://user-images.githubusercontent.com/10827302/40498552-fbb4cf48-5fb1-11e8-8254-3dbfda4d0a75.png)

If I connect to  https://172.18.106.125:8777/cas/,the message is below.
![image](https://user-images.githubusercontent.com/10827302/40498695-4ab55270-5fb2-11e8-8dc0-558632345e8d.png)

**Comment by kesmit13** [comment]
If you are using encryption, then you need to do two things. 1) change protocol='http' to protocol='https', and 2) set an environment variable called CAS_CLIENT_SSL_CA_LIST that points to the certificate used by the server. 

https://sassoftware.github.io/python-swat/encryption.html

**Comment by roy12369** [comment]
Hi @

**Comment by kesmit13** [comment]
By "binary", we mean CAS' proprietary binary protocol.  That is only included in the C extensions available on Linux (at the moment).  Now to the environment variable.  The environment here means the shell environment, not R environment.  So if you are going to set it from R, you would use:

```
Sys.setenv(CAS_CLIENT_SSL_CA_LIST='C:\\Users\\user\\Downloads\\trustedcerts.pem')
```

**Comment by roy12369** [comment]
Hi @kesmit13 ,
Got it!
But still failed to connect with the error.
```
> library(swat)
> Sys.setenv(CAS_CLIENT_SSL_CA_LIST="C:\\Users\\sasdemo\\Desktop\\trustedcerts.pem")
> conn=CAS("172.18.106.125", 8777, protocol="https",username="sasdemo01",password="demopw")
Error in value[[3L]](cond) : Unable to connect to any specified URL
```

**Comment by kesmit13** [comment]
I have to admit, I'm running out of ideas.  You could add the following parameters to with_verbose(...).  That will display everything that's going on.

```
data_out=TRUE, data_in=TRUE, info=TRUE, ssl=TRUE
```

**Comment by RyanWendt** [comment]
I seem to be having a similar problem. I am also attempting to use swat from RStudio on a windows machine.  When using port 8777 and protocol 'https' I get this error:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

Running the same parameters from the python version of the swat package allows me to successfully connect. Perhaps there is something going on on RStudio's side that prevents it from reading the needed environment variable?

**Comment by kesmit13** [comment]
Can you try and install the certificate using the instructions here?

http://www.thewindowsclub.com/manage-trusted-root-certificates-windows

**Comment by allej8** [comment]
I ran into similar issues.. ran the following using SWAT 1.2.1. I did NOT get this far using SWAT 1.2.0 from CRAN. The connection works using the exact same certification file and parameters in Python using their Python SWAT package.
```
library(swat)
Sys.setenv(CAS_CLIENT_SSL_CA_LIST='C:\\Users\\user\\SASCerts\\trustedcerts.pem')
conn <- swat::CAS("https://server.company.com:8777", user='user', password='pword')

# Error message #
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
```
Then tried with_verbose as recommended to provide more information.
```
httr::with_verbose(swat::CAS("https://server.company.com:8777", user='user', password='pword'), data_out=TRUE, data_in=TRUE, info=TRUE, ssl=TRUE)

# with_verbose output #
*  Hostname server.company.com was found in DNS cache
*    Trying 10.9.66.70...
*  TCP_NODELAY set
*  Connected to server.company.com (10.9.66.70) port 8777 (#1)
*  schannel: SSL/TLS connection with server.company.com port 8777 (step 1/3)
*  schannel: disabled server certificate revocation checks
*  schannel: sending initial handshake data: sending 184 bytes...
*  schannel: sent initial handshake data: sent 184 bytes
*  schannel: SSL/TLS connection with server.company.com port 8777 (step 2/3)
*  schannel: failed to receive handshake, need more data
*  schannel: SSL/TLS connection with server.company.com port 8777 (step 2/3)
*  schannel: encrypted data got 2727
*  schannel: encrypted data buffer: offset 2727 length 4096
*  schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
*  Closing connection 1
*  schannel: shutting down SSL/TLS connection with server.company.com port 8777
*  schannel: clear security context handle
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
```

**Comment by kesmit13** [comment]
@allej8 Try importing the certificate using the URL from my previous message.  It turns out that on Windows, the curl package ignores the environment variable specified.

**Comment by allej8** [comment]
Will do and report back. However, does that imply that the Python SWAT package doesn't make use of cURL while the R SWAT package does?

**Comment by kesmit13** [comment]
That's correct.  Python uses the requests package which oddly enough **will not** use the Windows certificate store.  It's a bit unfortunate that you have to configure certificates differently for the clients.  We're still trying to figure out ways to make it smoother.

**Comment by allej8** [comment]
Sorry for taking so long. I followed the steps in the link and ended up placing the trustedcerts.pem file in the Trusted Roots Certificate Store. Assuming the Sys.setenv() statement was no longer necessary because it's not looking in the os environment, this method still didn't make the CAS connection work. I also tried letting the Windows system choose where to place the file, and it ended up putting it in the Third Party Certificates Store. This also didn't work.

Was there a different step necessary to point R to the certificate?

**Comment by kesmit13** [comment]
I talked to someone else who is more familiar with these issues.  They think that you have the wrong certificate for that server.  They said to look in /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts, there should be a couple certs in .crt format.  Try using vault-microservices_1-ca.crt first, unless you are using a proxy, then use the httpproxy-microservices_1-ca.crt file.  For these, you can right click them and "Install Certificate" and select the Local Machine "Trusted Root Certification Authorities" store.

**Comment by allej8** [comment]
I'm not sure if you helped the fellow who made the original post... but the .crt files worked for me! Thank you very much!

**Comment by roy12369** [comment]
Hi @kesmit13 ,
Thanks for the reply. I have successfully connect to the CAS thru RStudio. Sense I have imported the .crt file before and still failed to connect. I found that it would fail if I used IP address to connect. After change it to host name, It works fine. Because I'm not familiar with this, do you know the reason?
Thanks!

**Comment by kesmit13** [comment]
@roy12369 You must use the same name in your SAS connection as was used to generate the certificate.  Certificates will always verify the name used, and it must match exactly.

As far as the different certificates go, I'll have to check with some colleagues as to why there are different requirements.

**Comment by kesmit13** [comment]
@roy12369 As far as the different certificate formats go, I think I'll defer to the explanation at the following URL.  The different certificates are essentially different ways of packaging them.  Each client has its own preferred format.

https://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file

I think that clears up all of the issues with this, so I'm going to count it as closed.
