### ISSUE TITLE
README installation instructions may require updating

### ISSUE THREAD

**Issue by ernestynne** [sassoftware/R-swat#13]
Currently when you start RStudio using the AWS SAS training image the following code snippet is displayed in an R script
```
install.packages('https://github.com/sassoftware/r-swat/releases/download/vX.X.X/r-swat-X.X.X-platform.tar.gz')
```
This code and the R-swat README refers to r-swat in lower case. After checking the release page I found that the ‘r’ is upper case. 

After I fixed that there were warnings when following the install instructions in the README (probably caused by the way RStudio and R are set up on the image and since the image has been wiped I cannot reproduce the exact code that I tried)
```
Warning: package is not available for R version 3.4.3
```
I got the swat package up and running using
```
install.packages('devtools')
library(devtools)
devtools::install_github(repo='sassoftware/R-swat')
library(swat)
```
Possible Actions
* Recommend that the README be updated to have an upper-case r when referring to the repo or release R-swat.
* It might also be useful to have the devtools instructions as an alternative install method for people who get stuck with all the other methods listed in the README.

**Comment by kesmit13** [comment]
@ernestynne Thanks for letting us know.  The AWS SAS training image must have an earlier version of the SWAT client.  The current README does use upper-case; however, I see that the first release used lower-case.

One thing to note about using devtools::install_github is that you will only get the source distribution, not the additional extension modules.  This means that you will only be able to connect to CAS using the REST interface, not the binary interface.  There are just a couple of things that the binary interface can do that the REST interface can't, and the REST interface will be a bit slower.  However, as long as you aren't transferring a lot of data back and forth, the difference should be minimal.

**Comment by mikemckiernan** [comment]
@ernestynne, I meant to say thank you too.
