### ISSUE TITLE
Python SWAT works but status 807ff008 for R-SWAT on the same JupyterHub server

### ISSUE THREAD

**Issue by JinnyBoy94** [sassoftware/R-swat#17]
Hi experts,

Title is pretty much self explanatory. 

Here are some extra details about the problem.
- JupyterHub and CAS are residing on the same RHEL server.
- Python-SWAT works just fine without any errors.
- R-SWAT V1.4.0
- Sys.getenv('CAS_CLIENT_SSL_CA_LIST') returns the desired destination of the .pem file
- When running the following code:
`conn <- swat::CAS('Some.Random.Server', 5570, protocol='http', username='ABCDEFG', password='abcdefg')`
The following is the result:
`Error in curl::curl_fetch_memory(url, handle = handle) :
  Recv failure: Connection reset by peer`
- When running the following code:
`conn <- swat::CAS('Some.Random.Server', 5570)`
The following is the result:
`ERROR: The TCP/IP negClientSSL support routine failed with status 807ff008.
ERROR: Failed to connect to host 'Some.Random.Server', port 5570.
Error in swat::errorcheck(sw_error) :
  Could not connect to 'Some.Random.Server' on port 5570.`

Hoping that someone has an idea what's going wrong...

**Comment by kesmit13** [comment]
The combination of protocol='http' and port=5570 seems suspect.  5570 is usually the binary protocol, not HTTP.  Try removing protocol='http'.

**Comment by kesmit13** [comment]
Sorry, I see that you did try removing that.  According to https://sassoftware.github.io/python-swat/encryption.html that certificate is not the correct one.  There are different certificates depending on which protocol you are using, so if you have it working with Python, it would be helpful to see the code you used to connect with that.

**Comment by JinnyBoy94** [comment]
Hi kesmit,

Thanks for replying.

The following is the code I used for Python swat.
`conn = swat.CAS('Some.Random.Server', 5570, 'ABCDEF', 'abcdef')
`
In both the R and Python kernel the CAS_CLIENT_SSL_CA_LIST points to 
> /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem

Regards,
Jin

**Comment by JinnyBoy94** [comment]
Update: I tried using the following code instead and it worked.
`conn <- swat.CAS('Some.Random.Server', 5570, username='ABCDEF'), password='abcdefg')

It seems that 807ff008 is not restricted to SSL certs issue. Would be nice if there is a way to highlight that credentials are needed to be supplied or credentials are invalid.

Regards,
Jin

**Comment by kesmit13** [comment]
Could you post your log both with and without authentication?  The SSL error messages should only appear for SSL issues.

**Comment by JinnyBoy94** [comment]
Sorry, my bad. Let me clarify the actual situation.

The error codes when running swat::CAS in R terminal is different from when running swat::CAS in an R kernel in a JupyterNotebook.

It is a strange behavior and I will post the logs for both the environments, with and without the authentication.

- R Kernel in a JupyterNotebook:
Without authentication
`Error in swat::errorcheck(sw_error): Could not connect to '172.27.152.39' on port 5570.
Traceback:

1. swat::CAS("172.27.152.39", 5570)
2. new(structure("CAS", package = "swat"), ...)
3. initialize(value, ...)
4. initialize(value, ...)
5. .Object$initialize(...)
6. swat::errorcheck(sw_error)
7. stop(m[[1]])`
With authentication
`NOTE: Connecting to CAS and generating CAS action functions for loaded
      action sets...
NOTE: To generate the functions with signatures (for tab completion), set 
      options(cas.gen.function.sig=TRUE).`

- R Terminal:
Without authentication
`ERROR: The TCP/IP negClientSSL support routine failed with status 807ff008.
ERROR: Failed to connect to host 'Some.Random.Server', port 5570.
Error in swat::errorcheck(sw_error) :
  Could not connect to 'Some.Random.Server' on port 5570.`
With authentication
`ERROR: The TCP/IP negClientSSL support routine failed with status 807ff008.
ERROR: Failed to connect to host 'Some.Random.Server', port 5570.
Error in swat::errorcheck(sw_error) :
  Could not connect to 'Some.Random.Server' on port 5570.`

Regards,
Jin

**Comment by kesmit13** [comment]
It's probably getting the same error in both.  Can you check the terminal where Jupyter notebook was started?  I believe the R client has an issue where the SSL errors come out in that terminal rather than where the R client is running.

**Comment by JinnyBoy94** [comment]
The JupyterHub server was started in the background by root user using the following code:
```nohup /opt/anaconda3/bin/jupyterhub -f /opt/anaconda3/etc/jupyterhub/jupyterhub_config.py > jupyterhub.log 2>&1 & ```

If you are referring to Jupyterhub logs, I do not see any logs when running swat commands.

**Comment by kesmit13** [comment]
Yes, I'm referring to your jupyterhub.log file.  I'm still not sure how just adding authentication would make an SSL error go away.  The client wouldn't be able to attempt to authenticate until the SSL connection is complete.
