### ISSUE TITLE
 Upload date format column to CAS

### ISSUE THREAD

**Issue by songpaper** [sassoftware/R-swat#19]
In Data Frame, one column is date format. 
Can I upload to CAS while maintaining the date format?
For now, just upload the date format, then it read in varchar format.

I am creating a job that uploads preprocessed data in R.
However, because the Plan of Prepare Data is executed in Viya(convert varchar to date), the data linked with the report is not updated automatically.
If i upload the data from R to CAS while maintaining the date column type, i don't need to execute the Plan of Prepare Data step.
So i simply upload the data from R to CAS and make the data associated with the report update automatically.

I am uploading data with the following code.
```
as.casTable(conn, dataframe, casOut=list(name="NEGO_AGG_R", caslib='PUBLIC', promote=TRUE))
```

Convert DataFrame to CAS dataframe using as.casDataFrame,
Can I convert a column types to Date with an option?
Or is there another method?
```
as.casDataFrame(df, name = "", label = "", title = "", attrs = list(),
col.labels = "", col.formats = "", col.attrs = list(),
col.sizes = list(), col.types = "", col.widths = 0)
```

**Comment by kesmit13** [comment]
If you happen to be running SAS Viya 3.4, there is a new sub-parameter to the `upload` action that you can use to specify a SAS informat (see http://support.sas.com/documentation/cdl/en/leforinforref/64790/HTML/default/viewer.htm#n0verk17pchh4vn1akrrv0b5w3r0.htm for possible informats).  You would specify the informat in the `importOptions.vars=` parameter.  Something like this:
```
cas.upload.frame(conn, dataframe, 
    importOptions=list(
       vars=list(
            datecolname=list(informat='DDMMYY')
        )
    ),
    casOut=list(name='NEGO_AGG_R', caslib='PUBLIC', promote=TRUE)
)
```

**Comment by songpaper** [comment]
I entered the code as below and an error occurred. 
cas.upload.frame(conn, data_detail, 
    importOptions=list(
       vars=list(
            계약일자=list(informat='YYYYMMDD')
        )
    ),
    casOut=list(name='song_test', caslib='PUBLIC', promote=TRUE)
)


The error details are as follows:

> If you happen to be running SAS Viya 3.4, there is a new sub-parameter to the `upload` action that you can use to specify a SAS informat (see http://support.sas.com/documentation/cdl/en/leforinforref/64790/HTML/default/viewer.htm#n0verk17pchh4vn1akrrv0b5w3r0.htm for possible informats). You would specify the informat in the `importOptions.vars=` parameter. Something like this:
> 
> ```
> cas.upload.frame(conn, dataframe, 
>     importOptions=list(
>        vars=list(
>             datecolname=list(informat='DDMMYY')
>         )
>     ),
>     casOut=list(name='NEGO_AGG_R', caslib='PUBLIC', promote=TRUE)
> )
> ```

**Comment by songpaper** [comment]
I entered the code as below and an error occurred. 
```
cas.upload.frame(conn, data_detail, 
    importOptions=list(
       vars=list(
            datecolumn=list(informat='YYYYMMDD')
        )
    ),
    casOut=list(name='song_test', caslib='PUBLIC', promote=TRUE)
)
```
The error details are as follows:
ERROR: Parameter 'importOptions.vars' is not recognized.
ERROR: Expecting one of the following as a subparameter to 'importOptions': fileType, ft.
ERROR: An attempt was made to convert parameter 'importOptions' from 'value_list' to one of a set of alternative types, but the conversion failed.
ERROR: The action stopped due to errors.

**Comment by kesmit13** [comment]
Try adding fileType='csv' as a sub-parameter to importOptions=.
