### ISSUE TITLE
Add casOut="mytablename" support to cas.read.xxx functions

### ISSUE THREAD

**Issue by mikemckiernan** [sassoftware/R-swat#2]
One of the features of SAS Cloud Analytic Services, is parameter coercion.  The current signature of cas.read.csv (for example) supports the following use:

`mytable <- cas.read.csv(conn, "/path/to/my/R/client/file.csv", casOut=list(name="mytable"))`

Because of parameter coercion, the function should be able to support the following use:

`mytable <- cas.read.csv(conn, "/path/to/my/R/client/file.csv", casOut="mytable")`

I've added this issue to request support for casOut="character" and casOut=list() support to the cas.read.xxx functions.

**Comment by jld23** [comment]
This is fixed by PR #3
