### ISSUE TITLE
Package Swat not available for R version 3.2+

### ISSUE THREAD

**Issue by jocobtt** [sassoftware/R-swat#20]
I have been trying to use Swat for a project in R but Swat only works on R versions that are 3.1 or lower. So I can't use it on any of the recent releases of R. Are there any plans to update the version of R that this package is able to run on?

**Comment by kesmit13** [comment]
What platform are you running on?  We've run it in various R versions including 3.4 and 3.5.

**Comment by jocobtt** [comment]
I have tried installing Swat on R studio and on a Cran mirrored R version as well, but both give me the same error saying that Swat isn't available for the version of R I am trying to run it on. 

Is there anything in particular that you did to get Swat to run on R version 3.4 or 3.5?

**Comment by kesmit13** [comment]
Are you installing it using the instructions in the README on Github?

**Comment by jocobtt** [comment]
Yes I am following the instructions but it is not working for the different versions of R that I have been trying (even when I try to install using a docker image of R with different versions etc.)

**Comment by kesmit13** [comment]
That's really odd.  We've installed it using various versions of R.  If you could give a complete log of what happens during an install, I'd like to see it.

**Comment by jocobtt** [comment]
The errors were different across the board. Sometimes I would have an issue with downloading httr or other times httr would install fine but then it would get held up with swat. I actually got it all installed in working just this morning now so whatever my issue was it resolved itself. Thanks for your help though!
