### ISSUE TITLE
Readme says binary connections are Linux only, but seem to be possible from Windows now

### ISSUE THREAD

**Issue by gwsas** [sassoftware/R-swat#22]
In the readme under https://github.com/sassoftware/R-swat#binary-and-rest-communication, it states

`The C libraries (and therefore binary communication) are supported for 64-bit Linux only. `

However, it appears that binary connections from R on Windows are now possible, so this statement might need updating/removal.

**Comment by kesmit13** [comment]
You are correct.  It's mentioned earlier in the README, but was missed in that spot.  It's fixed in 59f23ca71e6323cdfad42d2d0d461ccc861ce6d2.
