### ISSUE TITLE
Not able to Install R-swat-1.4.1-win64.tar.gz on windows client machine.

### ISSUE THREAD

**Issue by venkattoluchuri** [sassoftware/R-swat#23]
Hi,

I had able to setup Jupyter notebook can connect to CAS for Viya and we are good. Now I am trying to setup CAS to be run from R studio.

However, I have been following instructions from sassoftware github and stuck running below install package on my windows machine and given ERROR below.

install.packages('https://github.com/sassoftware/R-swat/releases/download/v1.4.1/R-swat-1.4.1-win64.tar.gz', repos=NULL, type='file')

> install.packages('https://github.com/sassoftware/R-swat/releases/download/v1.4.1/R-swat-1.4.1-win64.tar.gz', repos=NULL, type='file')
trying URL 'https://github.com/sassoftware/R-swat/releases/download/v1.4.1/R-swat-1.4.1-win64.tar.gz'
Content type 'application/octet-stream' length 48621202 bytes (46.4 MB)
downloaded 46.4 MB

* installing *source* package 'swat' ...
** libs
  running 'src/Makefile.win' ...
installing to C:/Program Files/R/R-3.2.2/library/swat/libs/x64
** R
** preparing package for lazy loading
Creating a generic function for 'print' from package 'base' in package 'swat'
Creating a generic function for 'nrow' from package 'base' in package 'swat'
Creating a generic function for 'ncol' from package 'base' in package 'swat'
Creating a generic function for 'colnames' from package 'base' in package 'swat'
Creating a generic function for 'rownames' from package 'base' in package 'swat'
Creating a generic function for 'head' from package 'utils' in package 'swat'
Creating a generic function for 'tail' from package 'utils' in package 'swat'
Creating a generic function for 'subset.data.frame' from package 'base' in package 'swat'
Creating a generic function for 'subset' from package 'base' in package 'swat'
Creating a generic function for 'unique' from package 'base' in package 'swat'
Creating a generic function for 'rbind' from package 'base' in package 'swat'
Warning: package 'dplyr' was built under R version 3.2.5
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'DBI'
Error : package or namespace load failed for 'dplyr'
Error : unable to load R code in package 'swat'
ERROR: lazy loading failed for package 'swat'
* removing 'C:/Program Files/R/R-3.2.2/library/swat'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.2.2\library" "C:/Users/vt7/AppData/Local/Temp/RtmpIRQ29x/downloaded_packages/R-swat-1.4.1-win64.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/vt7/AppData/Local/Temp/RtmpIRQ29x/downloaded_packages/R-swat-1.4.1-win64.tar.gz’ had non-zero exit status

**Comment by kesmit13** [comment]
I've never seen that error before.  I do see that there is an error before it even gets to swat though when loading DBI.  Can you try to install that manually first then install SWAT and see what happens?
```
 install.packages("DBI")
```

**Comment by venkattoluchuri** [comment]
Thank you this is resolved. Similar to SASPy can we connect to Grid 9.4 using R?

**Comment by kesmit13** [comment]
SWAT is only for connecting to CAS servers.  SAS 9.4 is a very different architecture and we don't currently have an R interface for that.

**Comment by venkattoluchuri** [comment]
We have SAS 9.4 Grid Architecture, if we want to enable running R on our SAS, what were the options and how to accomplish.

Regards,
Venkat
+91 9642454566

**Comment by tomweber-sas** [comment]
We don't have an R interface to SAS, like we have a Python interface to SAS (saspy). saspy fully supports the SAS Grid Architecture, but I'm afraid there isn't an R equivalent to saspy.

**Comment by venkattoluchuri** [comment]
Thank you Tom. Do we have any option to run R codes with in SAS then if we do not have R interface to run SAS ? if Yes, any steps please ?

Regards,
Venkat
+91 9642454566

**Comment by tomweber-sas** [comment]
Well, I'm not personally familiar with it, but there is some kind of support for executing R code from w/in a SAS session. Here's a link to a post that has information about this. I can also see if someone else who has more experience with this can provide more direct input ...
https://communities.sas.com/t5/General-SAS-Programming/Run-R-code-inside-SAS-easily/td-p/210116

**Comment by cjdinger** [comment]
See Rick Wicklin's post on this topic here: [Twelve advantages to calling R from the SAS/IML language](https://blogs.sas.com/content/iml/2013/11/25/twelve-advantages-to-calling-r-from-the-sasiml-language.html).  You do need SAS/IML, a part of SAS that offers a matrix-style language that should feel familiar to R users.

**Comment by venkattoluchuri** [comment]
Thank you Chris. Do we really need SAS/IML licensed for SAS 9.4 to run R on SAS ?

Regards,
Venkat
+91 9642454566

**Comment by cjdinger** [comment]
Yes, for this submit R technique to work you do need IML.  There are some other techniques that use system commands to run R from SAS.  [This GitHub project](https://github.com/sassoftware/enlighten-integration) has code for that.
