### ISSUE TITLE
Accessing CAS when running Viya on AWS

### ISSUE THREAD

**Issue by ALGW71** [sassoftware/R-swat#25]
Hi,

I am struggling to use SWAT to access the CAS controller on Viya set up on AWS (we set up according to the following guide: https://github.com/aws-quickstart/quickstart-sas-viya).

Would you be able to point out any differences in the "swat::CAS((...)" command that we need to apply in order to connect and run R/Python?

We tried connecting to various IP addresses, but received the error "Empty reply from server" when using different options (port 8777 and port 5570).

Any help would be much appreciated.

Kind Regards,
Alex

**Comment by kesmit13** [comment]
I have to admit that I haven't worked with AWS personally, but the way to connect should be the same regardless of where SAS Viya is installed.  You would need the hostname / IP address of the CAS controller, and that server needs to be accessible from where you are running Python / R (meaning that you need to open port 8777 or 5570 in the firewall).  The message "Empty reply from server" makes me think that the port may not be open.

**Comment by ALGW71** [comment]
Hi Kevin,

Many thanks for the quick response. I just found the documentation for SAS Viya quickstart on AWS - and it says in there the following:
"Connecting to CAS using the SWAT Python client via TCP port 5570 is not supported in the AWS Quick Start environment."

I assume that goes for R as well. So it must not be supported - we'll have to look at other SAS builds.

Many thanks for your reply. Happy to close the issue.

Kind Regards,
Alex

**Comment by kesmit13** [comment]
I missed that part.  Yes, that would apply to both Python and R, however, you can use the REST port of the CAS server (typically either 8777 for HTTP or 443 for HTTPS).  It works the same either way, the port 5570 uses a proprietary protocol that's a bit faster.  Using the REST port would look like this:
```
    # R
    conn <- swat::CAS('https://my-cas-controller.domain.com:443')

    # Python
    conn = swat.CAS('https://my-cas-controller.domain.com:443')
```

**Comment by ALGW71** [comment]
Hi Kevin,

Fantastic - I got it working now.

Many thanks,
Alex
