### ISSUE TITLE
How do I write an astore to a binary file?

### ISSUE THREAD

**Issue by pinduzera** [sassoftware/R-swat#26]
The title explain pretty much everything. How do I write an downloaded astore to a file?

In python it's easy:
``` python

s.loadactionset('aStore')

astore_name = "_C80O7P8PJUOIEXTSRM5VBDJC1_ast"

store=s.download(rstore= {"name": astore_name, 
                          "caslib": "Models"})

with open('savelocal.sasast','wb') as file:
   file.write(store['blob'])
```

But in R the store file comes as a list, now raw . I've tried through RAW, bytes etc but didn't achieve much 

``` r
loadActionSet(conn, "astore")

astore <- cas.astore.download(conn,
                    rstore =  list(name = astore_name, caslib = "Models")
                    )
class(astore) ### it's a list, simple saving it is not the binary astore. How do i do that?
filecon <- file("savelocal.sasast", "wb")

writeBin(astore, filecon) ## doesn't work, it only transforms vectors, not lists
```

If you can cover upload as well, because I can't figure out how to upload/read a blob in R

Thanks!

**Comment by kesmit13** [comment]
@pinduzera Is there a blob field in the list like in Python (i.e., astore$blob)?

**Comment by pinduzera** [comment]
> 
> 
> @pinduzera Is there a blob field in the list like in Python (i.e., astore$blob)?

Yes, that field exists, and it's not empty. 
The structure is something like:

``` r
list(blob = 
          list(length = numeric(),
                blob = character() )
    )
```

**Comment by kesmit13** [comment]
Are you using the most recent version of R SWAT? The value in astore$blob$data is probably what you are looking for, but it should be just astore$blob like in Python. I'm guessing this is the REST interface you are using. Do you have access to the binary port of the CAS server? That should work correctly. I'm thinking there may be a bug in the REST version, but I'm looking into it.

**Comment by pinduzera** [comment]
> 
> 
> Are you using the most recent version of R SWAT? The value in astore$blob$data is probably what you are looking for, but it should be just astore$blob like in Python. I'm guessing this is the REST interface you are using. Do you have access to the binary port of the CAS server? That should work correctly. I'm thinking there may be a bug in the REST version, but I'm looking into it.

Ok, I've managed to make a test with CAS insted of REST. It indeed comes directly as astore$blob, and the blob here is `raw`. So, I guess it is correct. As you've stated, the error should be at the REST interface. 
(only used swat 1.5.9000)

Now, to further complete the question.
When I try to upload this back, it fails.

``` r
## saving to be used somewhere else
con <- file("savelocal.sasast", "wb")
writeBin(object = astore_blob$blob, con = con)


### reading the file back
con <- file("savelocal.sasast", "rb")
astore_read <- readBin(con = con, what = raw(), 
                                     n = 24454977) ## n has to be guessed, or you can get it's size inside Viya or length(astore_blob$blob)
close(con)

astore_name = "_C80O7P8PJUOIEXTSRM5VBDJC1_ast"


cas.astore.upload(conn,
                  rstore =  list(name = astore_name, 
                                 caslib = "Models", replace = TRUE),
                  store = astore_read)
```
If I try to upload using CAS it just hangs and never completes
If I try through REST I get and empty list and the following error:

```
ERROR: An attempt was made to convert parameter 'store' from string to blob, but the conversion failed.
ERROR: The action stopped due to errors.
list()
--


 
```

**Comment by kesmit13** [comment]
I pushed some changes (1d79ed924778345a68eb39fdf5bb5345edb89344) to fix some of the issues you are seeing. The handling of binary parameters and results wasn't complete. You should now be able to send a raw data value as a store=, and the result should have a blob field with the correct value in it.

I was also able the score using an astore file that I uploaded using the binary interface, but I haven't had any luck with REST myself. I've contacted the server-side developers to look into it. Once I uploaded the file using the binary interface, I was successfully able to score using it.

Was your astore file created using the same CAS server that you are trying to upload from, or was it generated elsewhere?

**Comment by pinduzera** [comment]
> 
> 
> I pushed some changes ([1d79ed9](https://github.com/sassoftware/R-swat/commit/1d79ed924778345a68eb39fdf5bb5345edb89344)) to fix some of the issues you are seeing. The handling of binary parameters and results wasn't complete. You should now be able to send a raw data value as a store=, and the result should have a blob field with the correct value in it.
> 
> I was also able the score using an astore file that I uploaded using the binary interface, but I haven't had any luck with REST myself. I've contacted the server-side developers to look into it. Once I uploaded the file using the binary interface, I was successfully able to score using it.
> 
> Was your astore file created using the same CAS server that you are trying to upload from, or was it generated elsewhere?

Cool! Thanks for the quick fix.
I am first trying to make it work same server before trying different environments. It was created in the same place I was trying to upload to.

**Comment by kesmit13** [comment]
You might want to try uploading and doing an astore.describe action call on it to see if that returns the correct information.

**Comment by kesmit13** [comment]
@pinduzera Just looking over some issues today, did you ever get this to work?

**Comment by pinduzera** [comment]
Hi @kesmit13 .
I actually didn't have time to try this before.
Yes, it worked!
And thanks for the quality of life improvement where you added `astore$blob$data` and `astore$blob$length`, but as far as I understood this is only to http, when using cas it returns only `astore$blob`.  Just pointing out due to consistency.
Anyway, it is working beautifully!
Thanks a lot. We can close this issue

**Comment by kesmit13** [comment]
I thought both HTTP and binary should work the same way now. If not, I I'll have to fix the HTTP version so that it only returns `blob` like binary.
