### ISSUE TITLE
Not available for 3.6.3 or 4.0.3

### ISSUE THREAD

**Issue by komaiat** [sassoftware/R-swat#28]
I tried install.packages('swat') for R versions 3.6.3 and 4.0.3 and it appears it is unavailable for either. Which version of R is necessary to install this package?

**Comment by kesmit13** [comment]
It works for all versions of R >= 3.3, however, you need to use the instructions at https://github.com/sassoftware/R-swat/releases/tag/v1.6.0. The SWAT package includes pre-compiled binaries which aren't allowed in the normal channels, so they can only be installed from a tar.gz file.
