### ISSUE TITLE
retrieving count(*) from fedSQL query doesn't work correctly

### ISSUE THREAD

**Issue by j-honnacker** [sassoftware/R-swat#30]
Hi,

When issuing a fedSQL group by query with `count(*)`, the `count(*)` column that is retrieved has the same value in every row (correct value for first row).

**Example:**
`cas.fedSql.execDirect(conn, query="SELECT job, count(*) as cnt FROM casuser.hmeq GROUP BY job ORDER BY job;")`

![R](https://user-images.githubusercontent.com/15622207/120109296-cad0ac00-c136-11eb-950c-412868e57a2d.PNG)

The correct result when using Python-swat:
`conn.fedSql.execDirect(query="SELECT job, count(*) as cnt FROM casuser.hmeq GROUP BY job ORDER BY job;")`

![Python](https://user-images.githubusercontent.com/15622207/120109399-47638a80-c137-11eb-914c-9735ebd69a2c.PNG)

**Comment by kesmit13** [comment]
Fixed in v1.6.3
