### ISSUE TITLE
Connecting to CAS from R-SWAT fails with error: errorcheck(sw_value) : Could not decode table data

### ISSUE THREAD

**Issue by irchum** [sassoftware/R-swat#49]
Hi All,
This is Ira, member of SAS Technical Support. 

1) I have a customer who opened a Track with us as he gets below error when connecting to CAS from R-SWAT. He performed the following steps
- he installed [R 4.3.1](https://cran.r-project.org/bin/windows/base/) on Windows 11
- he installed required packages including 'dplyr', 'httr','jsonlite' and swat within R directly using URL
- he imported Viya server certiciates into Windows
- he created .authinfo file in %HOMEPATH% that contains:
host avisia-cluster-02.localdomain user crapine password *************
- Connect to CAS
> library('swat')
SWAT 1.8.4
> Sys.setenv(CASCLIENTDEBUG=1)
> conn <- swat::CAS('avisia-cluster-02.localdomain', 5570)

[1] "NOTE: HOME: C:\\Users\\Avisia\\OneDrive\\Documents"
[1] "NOTE: HOMEDRIVE: C:"
[1] "NOTE: HOMEPATH: \\Users\\Avisia"
[1] "NOTE: Process owner identity is: DESKTOP-26DDQPG/Avisia"
[1] "NOTE: Reading authinfo file: C:\\Users\\Avisia\\.authinfo"
[1] "NOTE: Matching host: avisia-cluster-02.localdomain"
[1] "NOTE: Matching port: 5570"
[1] "NOTE: Matching user: NONE"
[1] "NOTE: Using authinfo host definition: host avisia-cluster-02.localdomain user crapine password ************"
[1] "NOTE: Client is using userid=crapine, password=***"
[1] "NOTE: Client is using the userpass identity provider"
[1] "NOTE: Sent challenge length 138"
[1] "NOTE: Received response length 56"
[1] "NOTE: User crapine connected to CAS using user/pass."
NOTE: Connecting to CAS and generating CAS action functions for loaded
      action sets...
**Erreur dans swat::errorcheck(sw_value) : Could not decode table data.**

2) I have reproduced the problem on my environment. I have the same error.
Erreur dans swat::errorcheck(sw_value) : Could not decode table data.

I have checked corresponding CAS log. I don't see any particular error.
INFO  2023-08-04 11:14:14.802 [cas] - MAIN irchum 486 [casgeneral.c:4997] - Launched session controller. Process ID is 14577. [index:00004750]
INFO  2023-08-04 11:14:14.846 [cas] - 14577 irchum MAIN [cas.c:2310] - Starting Cloud Analytic Services driver, host=viya35jm.ts.sashq-d.openstack.sas.com, id=0, role=session controller. [index:00000007]
INFO  2023-08-04 11:14:14.848 [cas] - 14577 irchum MAIN [tkcsesinst.c:748] - Successfully created session 0bfd4045-b371-eb40-857e-949b6e8e0eb1. [index:00000007]
INFO  2023-08-04 11:14:14.851 [cas] - 14577 irchum 486 [tkhttpserver.c:1353] - Starting HTTP server 'viya35jm.ts.sashq-d.openstack.sas.com', minPort=0 maxPort=0 [index:00000007]
INFO  2023-08-04 11:14:14.853 [cas] - 14577 irchum 486 [tkhttpserver.c:1438] - HTTP Server 'viya35jm.ts.sashq-d.openstack.sas.com' listening on port 36945. [index:00000007]
INFO  2023-08-04 11:14:14.877 [cas] - 14577 irchum 486 [cashttp.c:1936] - HTTP server is authenticating connections. [index:00000007]
INFO  2023-08-04 11:14:14.877 [cas] - 14577 irchum 486 [cashttp.c:1983] - HTTP server listening on HTTPS port 36945. [index:00000007]
INFO  2023-08-04 11:14:15.166 [cas] - 14577 irchum 486 [tkcasaimp.c:4504] - ++ action sessionProp.setFmtSearch / fmtLibNames={'CASFORMATS', 'PASCAL', 'SASSUPPLIEDFORMATS', 'ADDITIONALFORMATS'}; [index:00000007]
INFO  2023-08-04 11:14:15.167 [cas] - 14577 irchum 486 [tkcasaimp.c:6460] -  -- 'sessionProp.setFmtSearch' SUCCESSFUL. [index:00000007]
NONE  2023-08-04 11:14:15.167 [cas] - INFO  14577 irchum 486 - 2.0_Consumption: CAS Action 'sessionProp.setFmtSearch' $ licensed cores 0, available cores 16, starting core 0 $ elapsed time 0.002117 seconds $ cpu time 0.001550 seconds (73.22%) $ total memory 125.75G $ memory 425.00K (0.00%) $ RC 0
INFO  2023-08-04 11:14:15.254 [cas] - 14577 irchum 486 [tkcasaimp.c:4504] - ++ action builtins.reflect / action='builtins.reflect', _messageLevel='error'; [index:00000007]
INFO  2023-08-04 11:14:15.255 [cas] - 14577 irchum 486 [tkcasaimp.c:6460] -  -- 'builtins.reflect' SUCCESSFUL. [index:00000007]
NONE  2023-08-04 11:14:15.255 [cas] - INFO  14577 irchum 486 - 2.0_Consumption: CAS Action 'builtins.reflect' $ licensed cores 0, available cores 16, starting core 0 $ elapsed time 0.001132 seconds $ cpu time 0.001054 seconds (93.11%) $ total memory 125.75G $ memory 227.16K (0.00%) $ RC 0
INFO  2023-08-04 11:14:15.403 [cas] - 14577 irchum 486 [tkcasaimp.c:4504] - ++ action builtins.about / _messageLevel='error'; [index:00000007]
INFO  2023-08-04 11:14:15.403 [cas] - 14577 irchum 486 [tkcasalic.c:466] - Opening license file '/opt/sas/viya/config/etc/cas/default/sas_license.txt'. [index:00000007]

NONE  2023-08-04 11:14:15.407 [cas] - INFO  14577 irchum 486 - 2.0_Consumption: CAS Action 'builtins.about' $ licensed cores 0, available cores 16, starting core 0 $ elapsed time 0.004038 seconds $ cpu time 0.003985 seconds (98.69%) $ total memory 125.75G $ memory 388.22K (0.00%) $ RC 0

INFO  2023-08-04 11:14:15.407 [cas] - 14577 irchum 486 [tkcasaimp.c:6460] -  -- 'builtins.about' SUCCESSFUL. [index:00000007]

NONE  2023-08-04 11:14:15.790 [vault] - {"time":"2023-08-04T09:14:15.789988593Z","type":"request","auth":{"client_token":"hmac-sha256:9d2db20255f9c099eef6adfa86ba38c529114d06ba4820baecb6e4e8a97d0684","accessor":"ihD0Zqoq2ZTQ7FiGeSZ31d6M","display_name":"token","policies":["default","pgpoolc"],"token_policies":["default","pgpoolc"],"token_type":"service"},"request":{"id":"0377110b-4ec0-dc9f-7293-9c5e91cdbc65","operation":"read","client_token":"hmac-sha256:9d2db20255f9c099eef6adfa86ba38c529114d06ba4820baecb6e4e8a97d0684","client_token_accessor":"ihD0Zqoq2ZTQ7FiGeSZ31d6M","namespace":{"id":"root"},"path":"secret/application/postgres/dba","remote_address":"10.104.81.73"}}

3) The following JIRA was opeend for similar issue last year. The issue occurred  when using R 4.2.0
https://rndjira.sas.com/browse/COMPUTESVCS-35205

Do you have any thought on this issue? 

Thanks
Ira

**Comment by bkemper24** [comment]
On Windows, the binary connection does not work with R 4.2 or later.  This issue is under investigation.

**Comment by michaelwalshe** [comment]
Hi, I've been runnning into the same issue with R 4.3.1 (Cannot decode table data on connecting), on a machine which I have confirmed can connect via Python. Is there any progress on this issue?

**Comment by bkemper24** [comment]
Yes, I expect to have a new release containing the fix published at the end of the month

**Comment by bkemper24** [comment]
The fix for R4.2 and later running on windows is now available in R-swat release [1.9.0](https://github.com/sassoftware/R-swat/releases/tag/v1.9.0)
