### ISSUE TITLE
gen.functions, get action set case from the server instead of the user

### ISSUE THREAD

**Issue by mikemckiernan** [sassoftware/R-swat#6]
In gen.functions, we reuse what the user typed in for the action set (TABLE or Table) when generating functions instead of reading it off the result that comes back from listActions.

> x <- casRetrieve(s, "listActions" actionSet="Table")
> ls(x$results)
[1] "table"

We want cas.table.loadTable() instead of cas.Table.loadTable().

**Comment by jld23** [comment]
Assigning to Tom since he maintains this function.

**Comment by tomweber-sas** [comment]
this is fixed in the tomtest1 branch

**Comment by tomweber-sas** [comment]
tomtest1 merged to master, so this is fixed.
